### ISSUE TITLE
Error when using style loader

### ISSUE THREAD

**Issue by pdeva** [webpack/style-loader#80]
This is the output:

```
ERROR in ./~/css-loader!./ts/styles.css
Module build failed: CssSyntaxError: /Users/pdeva/code/dsgui/node_modules/style-loader/index.js!/Users/pdeva/code/dsgui/node_modules/css-loader/index.js!/Users/pdeva/code/dsgui/ts/styles.css:1:4: Unknown word
// style-loader: Adds some css to the DOM by adding a <style> tag
   ^

    at Input.error (/Users/pdeva/code/dsgui/node_modules/css-loader/node_modules/postcss/lib/input.js:61:21)
    at Parser.unknownDecl (/Users/pdeva/code/dsgui/node_modules/css-loader/node_modules/postcss/lib/parser.js:472:26)
    at Parser.decl (/Users/pdeva/code/dsgui/node_modules/css-loader/node_modules/postcss/lib/parser.js:227:22)
    at Parser.word (/Users/pdeva/code/dsgui/node_modules/css-loader/node_modules/postcss/lib/parser.js:135:30)
    at Parser.loop (/Users/pdeva/code/dsgui/node_modules/css-loader/node_modules/postcss/lib/parser.js:60:26)
    at parse (/Users/pdeva/code/dsgui/node_modules/css-loader/node_modules/postcss/lib/parse.js:25:12)
    at new LazyResult (/Users/pdeva/code/dsgui/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:57:24)
    at Processor.process (/Users/pdeva/code/dsgui/node_modules/css-loader/node_modules/postcss/lib/processor.js:36:16)
    at processCss (/Users/pdeva/code/dsgui/node_modules/css-loader/lib/processCss.js:186:11)
    at Object.module.exports (/Users/pdeva/code/dsgui/node_modules/css-loader/lib/loader.js:22:2)
 @ ./ts/main.js 7:10-37

```

This is the command I used to run webpack:

```
webpack-dev-server --progress --colors -hot      
```

This is my webpack.config.js:

```
var path = require('path');
var webpack = require('webpack');

module.exports = {
  devServer: {
        hot: true,
        progress: true,
        colors: true,
        historyApiFallback: true
    },
    entry: [
      'webpack-dev-server/client?http://localhost:8080', // WebpackDevServer host and port
      'webpack/hot/only-dev-server', // "only" prevents reload on syntax errors
      "./ts/main.js"
    ],
    output: {
        path: '.',
        filename: "bundle.js"
    },
    module: {
      loaders: [
          { test: /\.css$/, loader: "style!css" },
          {
            test: /components\\(.*)\.js$/,
            loaders: ['react-hot'],
            include: path.join(__dirname, 'ts')
          }
    ]

    }
};

```

What am i doing wrong?

**Comment by bebraw** [comment]
Can you set up a standalone example? It's easier to study the issue that way. I don't see anything obviously wrong with your configuration.

**Comment by tizmagik** [comment]
I _think_ what's going on is that when you run `webpack-dev-server --progress --colors -hot` and also define the dev server hot reload in the entry config,
``
    entry: [
      'webpack-dev-server/client?http://localhost:8080', // WebpackDevServer host and port
      'webpack/hot/only-dev-server', // "only" prevents reload on syntax errors
```

You are essentially including the dev server twice. You should do one or the other (via commandline or via webpack config).

**Comment by SpaceK33z** [comment]
Closing due to inactivity.
Note that @tizmagik was right, you were including hot reload twice.
